import { v1 } from "uuid";
import type { CartItem } from "../../../../features/cart/ui/slice-cart";
import animeImage from "../../../../assets/images/anime.jpg";
import onePice from "../../../../assets/images/OnePice.webp";

export const initialProducts: CartItem[] = [
  {
    id: v1(),
    title: "Product 1",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  {
    id: v1(),
    title: "Product 2",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  {
    id: v1(),
    title: "Product 3",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  { id: v1(), title: "Product 4", image: onePice, price: 100, quantity: 1 },
  {
    id: v1(),
    title: "Product 5",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  { id: v1(), title: "Product 6", image: onePice, price: 100, quantity: 1 },
  {
    id: v1(),
    title: "Product 7",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  { id: v1(), title: "Product 8", image: onePice, price: 100, quantity: 1 },
  {
    id: v1(),
    title: "Product 9",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  { id: v1(), title: "Product 10", image: onePice, price: 100, quantity: 1 },
  {
    id: v1(),
    title: "Product 11",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  {
    id: v1(),
    title: "Product 1",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  {
    id: v1(),
    title: "Product 2",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  {
    id: v1(),
    title: "Product 3",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  { id: v1(), title: "Product 4", image: onePice, price: 100, quantity: 1 },
  {
    id: v1(),
    title: "Product 5",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  { id: v1(), title: "Product 6", image: onePice, price: 100, quantity: 1 },
  {
    id: v1(),
    title: "Product 7",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  { id: v1(), title: "Product 8", image: onePice, price: 100, quantity: 1 },
  {
    id: v1(),
    title: "Product 9",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  { id: v1(), title: "Product 10", image: onePice, price: 100, quantity: 1 },
  {
    id: v1(),
    title: "Product 11",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  {
    id: v1(),
    title:
      "Product dsaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    image: onePice,
    price: 100,
    quantity: 1,
  },
  {
    id: v1(),
    title: "Product 13",
    image: animeImage,
    price: 100,
    quantity: 1,
  },
  { id: v1(), title: "Product 14", image: onePice, price: 100, quantity: 1 },
];
